- name: Orchestrate VMs (rolling restart)
  hosts: all
  serial: 1
  tasks:
    - name: Reboot host
      ansible.builtin.reboot:
        msg: Reboot initiated by Ansible
      become: true

    - name: Check uptime of host
      ansible.builtin.command: uptime
      register: uptime_result

    - name: Print uptime
      ansible.builtin.debug:
        var: uptime_result.stdout
